services:
  quickstart:
    build:
      context: .
#    stdin_open: true # docker run -i
#    tty: true        # docker run -tpy
    command: flask run -h 0.0.0.0 -p 5000
    ports:
      - "5000:5000"
    volumes:
      - ./:/opt/

  test:
    build:
      context: .
    command: pytest -sv pytesting.py
    volumes:
      - ./:/opt/



